### ISSUE TITLE
html sections

### ISSUE THREAD

**Issue by rimmesbe** [xaandev/prj-rev-bwfs-dasmoto#1]
See how you have naturally organized the html into different sections. Make it official and wrap them in div elements. Move the id from the h2 into the div to work as a section label and uniquely target the h2s by chaining that: #brushes h2 { }
<img width="122" alt="screen shot 2017-06-28 at 1 57 34 pm" src="https://user-images.githubusercontent.com/9957628/30490963-a86fe28c-9a09-11e7-84a6-f11294650f56.png">
https://github.com/xaandev/prj-rev-bwfs-dasmoto/blob/master/dasmotos/index.html#L15-L18

**Comment by xaandev** [comment]
Cleaned up the organization structure by adding <div> elements.
