### ISSUE TITLE
setting page font

### ISSUE THREAD

**Issue by rimmesbe** [xaandev/prj-rev-bwfs-dasmoto#3]
You are setting the font-family in each selector, this is inefficient. Imagine if this was a much larger project, it would waste a lot of time. Instead set the page font through inheritance: 
html { font-family: Helvetica; }
Now all elements will inherit this font from html.

https://github.com/xaandev/prj-rev-bwfs-dasmoto/blob/master/dasmotos/resources/css/style.css#L3

**Comment by xaandev** [comment]
Set the font-family in the html document instead of in each section.
