### ISSUE TITLE
css class names

### ISSUE THREAD

**Issue by rimmesbe** [xaandev/prj-rev-bwfs-dasmoto#5]
The convention for css class names is now to name them after the component they are styling. You used the convention where the class name describes the style change, which is an outdated convention. I would also try to keep numbers out of class names in most cases.
.price { }
This describes the component being styled, the price text.

https://github.com/xaandev/prj-rev-bwfs-dasmoto/blob/master/dasmotos/resources/css/style.css#L30

**Comment by xaandev** [comment]
Modified class name to describe the component instead of the style change.
