### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [xaandev/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the page look good. You used some good techniques and kept your code organized. Take a look at the issues I created and see if you can implement the changes. They will help you optimize your efficiency and organization which will be very important as projects grow in size. Here are some good tips as well: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by xaandev** [comment]
Thanks for the feedback.  Fixed all of the issues as described in each section.
